corrections

diff --git a/UserRoot/zshrc b/UserRoot/zshrc
--- a/UserRoot/zshrc
+++ b/UserRoot/zshrc
@@ -8,9 +8,6 @@ fi
 # If you come from bash you might have to change your $PATH.
 # export PATH=$HOME/bin:/usr/local/bin:$PATH
 
-# Path to your oh-my-zsh installation.
-export ZSH="$HOME/.oh-my-zsh"
-
 # Set name of the theme to load --- if set to "random", it will
 # load a random theme each time oh-my-zsh is loaded, in which case,
 # to know which specific one was loaded, run: echo $RANDOM_THEME
@@ -99,8 +96,6 @@ plugins=(
   iterm2
   ) 
 
-source $ZSH/oh-my-zsh.sh
-
 # User configuration
 
 # export MANPATH="/usr/local/man:$MANPATH"
@@ -134,8 +129,48 @@ export HUB_PROTOCOL=https
 if (( ! ${fpath[(I)/usr/local/share/zsh/site-functions]} )); then
   FPATH=/usr/local/share/zsh/site-functions:$FPATH
 fi
+# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
+# Initialization code that may require console input (password prompts, [y/n]
+# confirmations, etc.) must go above this block; everything else may go below.
+if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
+  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
+fi
 
-source ~/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme
+# Source Prezto
+if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
+  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
+fi
+
+# Init zplug
+source ~/.zplug/init.zsh
+
+# Select zplug plugins
+zplug "clvv/fasd"
+zplug "junegunn/fzf"
+zplug "yuhonas/zsh-aliases-lsd"
+zplug "romkatv/powerlevel10k", as:theme, depth:1
+
+# Make sure that plugins are installed
+if ! zplug check --verbose; then
+    printf "Installing missing zplug plugins...\n"
+    zplug install
+fi
+
+# Load Zplug plugins
+zplug load
+
+# Define utility functions and aliases
+backup_with_timestamp() {
+    # Creates a timestamped backup of the given file or directory
+    BACKUP_NAME="$1_backup_$(date +%Y-%m-%d_%H:%M:%S)"
+    cp -r "$1" "$BACKUP_NAME"
+    echo "Created backup at \"./$BACKUP_NAME\""
+    unset BACKUP_NAME
+}
+alias ..="cd .."
+alias ...="cd ../.."
+alias ....="cd ../../.."
+alias bat="batcat"
 
 # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
 [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
